[features]
seeds = false
skip-lint = false
[programs.localnet]
daoship_programs = "9Jsfy18hxoXx1qWcWDRp9X6MF87bx1YRBznm41tFTyEh"
[programs.devnet]
daoship_programs = "9Jsfy18hxoXx1qWcWDRp9X6MF87bx1YRBznm41tFTyEh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
